radar/urls.py
from django.urls import path
from . import views

app_name = 'radar'
urlpatterns = [
    path('', views.school_list, name='school_list'),
    path('college/detail/<int:pk>/', views.detail, name='detail'),
    path('college/detail_api/', views.ajax_detail, name='detail_api'),
    path('college/search_api/', views.ajax_search, name='search_api'),
    path('college/compare_api/', views.ajax_compare, name='compare_api')
]

yaxue/urls.py
from django.contrib import admin
from django.urls import path, include
from radar.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('radar/', include('radar.urls')),
    path('', Home, name='home')
]

radar/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Test(models.Model):
    name = models.CharField(max_length=128)
    student_size = models.IntegerField(blank=True, null=True)
    avg_net_price = models.IntegerField(blank=True, null=True)
    median_earnings = models.IntegerField(blank=True, null=True)
    predominant = models.CharField(max_length=128, blank=True, null=True)
    ddsdd = models.CharField(max_length=12)

    class Meta:
        managed = True
        db_table = 'test'

class College(models.Model):
    college_name = models.CharField(max_length=128, db_column='college', unique=True)
    state = models.CharField(max_length=32, blank=True, null=True)
    city = models.CharField(max_length=32, blank=True, null=True)
    cost = models.FloatField(blank=True, null=True)
    student_size = models.IntegerField(blank=True, null=True)
    avg_price = models.FloatField(blank=True, null=True)
    percent_greater_than_25k = models.FloatField(blank=True, null=True)
    predominant = models.CharField(max_length=64, blank=True, null=True)
    consumer_rate = models.FloatField(blank=True, null=True)
    type = models.CharField(max_length=32, blank=True, null=True)
    position = models.CharField(max_length=32, blank=True, null=True)

    def __str__(self):
        return self.college_name

    class Meta:
        db_table = 'college'
        unique_together = (('id', 'college_name'),)


class CollegeDetail(models.Model):
    college_name = models.ForeignKey(College, models.DO_NOTHING, to_field='college_name', db_column='college')
    year = models.CharField(max_length=16)
    acceptance_rate = models.FloatField(blank=True, null=True)
    student_count = models.IntegerField(blank=True, null=True)
    sat_math = models.CharField(max_length=16, blank=True, null=True)
    sat_critical_reading = models.CharField(max_length=16, blank=True, null=True)
    sat_writing = models.CharField(max_length=16, blank=True, null=True)
    act_math = models.CharField(max_length=16, blank=True, null=True)
    act_writing = models.CharField(max_length=16, blank=True, null=True)
    act_cumulative = models.CharField(max_length=16, blank=True, null=True)
    act_english = models.CharField(max_length=16, blank=True, null=True)
    full_time = models.FloatField(blank=True, null=True)
    part_time = models.FloatField(blank=True, null=True)

    def __str__(self):
        return ':'.join([self.year, self.college_name.college_name])

    class Meta:
        db_table = 'college_detail'
        unique_together = (('year', 'college_name'),)


class Major(models.Model):
    college_name = models.ForeignKey(College, models.DO_NOTHING, to_field='college_name', db_column='college')
    year = models.CharField(max_length=16)
    major = models.CharField(max_length=128)
    credential = models.CharField(max_length=64, blank=True, null=True)
    graduates_count = models.IntegerField(blank=True, null=True)
    avg_earning = models.CharField(max_length=32, blank=True, null=True)

    def __str__(self):
        return ':'.join([self.year, self.major])

    class Meta:
        db_table = 'major'


class PayAllBachelors(models.Model):
    rank = models.IntegerField()
    college_name = models.CharField(max_length=64, db_column='college')
    type = models.CharField(max_length=64, blank=True, null=True)
    early_career_pay = models.CharField(max_length=64, blank=True, null=True)
    mid_career_pay = models.CharField(max_length=64, blank=True, null=True)
    high_meaning = models.CharField(max_length=16, blank=True, null=True)
    stem_degrees = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        db_table = 'pay_all_bachelors'
        unique_together = (('id', 'rank'),)


class PayBachelors(models.Model):
    rank = models.IntegerField()
    college_name = models.CharField(max_length=64, db_column='college')
    type = models.CharField(max_length=64, blank=True, null=True)
    early_career_pay = models.CharField(max_length=64, blank=True, null=True)
    mid_career_pay = models.CharField(max_length=64, blank=True, null=True)
    high_meaning = models.CharField(max_length=16, blank=True, null=True)
    stem_degrees = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        db_table = 'pay_bachelors'
        unique_together = (('id', 'rank'),)


class PayCity(models.Model):
    state = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    pay = models.CharField(max_length=64, blank=True, null=True)
    hourly_pay = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        db_table = 'pay_city'


radar/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import JsonResponse, Http404, HttpResponse, HttpResponseRedirect
from .models import College, CollegeDetail
import json, time


def timer(func):  #  计时装饰器
    def wrapper(*args):
        time_start = time.time()
        res = func(*args)
        time_end = time.time()
        print('耗时：{} 秒'.format(round(time_end - time_start, 5)))
        return res
    return wrapper
# Create your views here.

def school_list(request):  #  全学校列表页
    data = College.objects.values('college_name', 'id')
    if not data:
        raise Http404
    else:
        return render(request, 'radar/school_list.html', {'data': data})

def detail(request, pk):  #  详情页，雷达图
    return render(request, 'radar/radar_pic.html', {'pk': pk})

def ajax_detail(request):  #  学校详情json接口
    data = get_object_or_404(College, id=request.GET['pk'])
    college_name = data.college_name
    detail = data.collegedetail_set.filter(year='latest').first()
    context = {
        'detail': [{
            'college_name': college_name,
            'student_count': detail.student_count,
            'full_time': detail.full_time,
            'part_time': detail.part_time}],
        }
    return JsonResponse(context)

@timer
def ajax_search(request):  #  搜索框学校名json接口
    keywords = request.GET['keywords']
    result = College.objects.filter(college_name__icontains=keywords).values('college_name', 'id')[:5]
    if not result:
        raise Http404
    else:
        result = result[:]  #  QuerySet -> List
        return JsonResponse(result, safe=False)

def Home(request):  #  主页重定向
    return HttpResponseRedirect(reverse('radar:school_list'))

@timer
def ajax_compare(request):
    c = [request.GET['c1'], request.GET['c2']]
    context = {
        'detail': []
    }
    for i in c:
        data = get_object_or_404(CollegeDetail, college_name=i, year='latest')
        res = {
            'college_name': i,
            'student_count': data.student_count,
            'full_time': data.full_time,
            'part_time': data.part_time,
            'acceptance_rate': data.acceptance_rate
        }
        context['detail'].append(res)
    return JsonResponse(context)

radar/templates/radar/radar_pic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{{ pk }}雷达图</title>
    <link rel="stylesheet" type="text/css" href="{% static 'radar/css/jquery-ui.min.css' %}">
    <script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/echarts/3.7.1/echarts.min.js"></script>
    <script src="{% static 'radar/js/radar_draw.js' %}"></script>
    <script src="{% static 'radar/js/jquery-ui.min.js' %}"></script>
</head>
<body>
    <div id="chart" style="height: 700px;width: 1200px">
        <script>
            $(document).ready(function() {
                let radar_chart = echarts.init(document.getElementById("chart"));
                $.getJSON("{% url 'radar:detail_api' %}", {pk: '{{ pk }}'}, function(json){
                    let x = get_option(json);
                    radar_chart.setOption(x);
                    $('#c1').val(json.detail[0].college_name);
                })
            });
        </script>
    </div>
    <div>
        请输入学校名：<br/>
        <input type="text" id="search-text" name="q" autocomplete="off">
    </div>
    <div style="text-align:center;vertical-align:middle;">
        <form action="javascript:void(0)" method="get">
            <input readonly="true" id='c1'><button onclick="clear_text('c1')">取消</button>
            <br>
            <input readonly="true" id='c2'><button onclick="clear_text('c2')">取消</button>
            <br>
            <button type="button" id="compare_button">比较</button>
        </form>
    </div>
     <script>
        $(document).ready(function(){
            $("#search-text").keyup(function(){
                let q = $("#search-text").val();                         
                $.get("{% url 'radar:search_api' %}",{keywords: q}, function(data){    
                        $('#search-text').autocomplete({
                            source:function(x){
                                let res = [];
                                for (let i=x.length-1;i>=0;i--){
                                    res.push(x[i]['college_name']);
                                }
                                return res;
                            }(data),
                            delay: 10,
                            mustMatch: true,
                            select: function(e, ui) {
                                if ($('#c1').val() == "") {  
                                    $('#c1').val(ui.item.value);
                                } else {
                                    $('#c2').val(ui.item.value);
                                }
                            }
                        });
                    })
                });
            });
        $('#compare_button').on('click', function() {
            let college1 = $('#c1').val(), college2 = $('#c2').val();
            if (college1==""||college2=="") {
                alert('需选择两所学校进行对比');
            } else {
                $.getJSON("{% url 'radar:compare_api' %}", {c1: college1, c2: college2}, function(json){
                    let radar_chart = echarts.init(document.getElementById("chart"));
                    let x = get_option(json);
                    radar_chart.setOption(x);
                })
            }
        });
    </script>
</body>
</html>

radar/templates/radar/school_list.html
<!DOCTYPE html>
<html lang="cn">
<head>
   <meta charset="UTF-8">
   <title>Document</title>
</head>
<body>
    {% for i in data %}
        <a href="{% url 'radar:detail' i.id %}">{{ i.college_name }}</a>
        <br>
    {% endfor %}
</body>
</html>